services:
  db:
    container_name: postgresql-ecommerce
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ecommerce-sql
    volumes:
      - D:/sql/docker/compose-file/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-docker
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5055:80"
    networks:
      - spring-docker
networks:
  spring-docker:
    driver: bridge